global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: '/metrics'

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8002']
    metrics_path: '/metrics'

  - job_name: 'budget-service'
    static_configs:
      - targets: ['budget-service:8003']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8004']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8005']
    metrics_path: '/metrics'
